export const actionTypes = {
  FETCHING_START: 'FETCHING_START',
  FETCHING_SUCCESS: 'FETCHING_SUCCESS',
  FETCHING_ERROR: 'FETCHING_ERROR',
  ADD_TO_CART: 'ADD_TO_CART',
  ADD_TO_WISH: 'ADD_TO_WISH',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  REMOVE_FROM_WISH: 'REMOVE_FROM_WISH',

}